### ISSUE TITLE
No plugin files just screenshots

### ISSUE THREAD

**Issue by 3dprintedmac** [nkuvyrkin/Ultimaker-Cura-v5.x-QIDI-Printer-Plugin#2]
Not sure if i'm missing something, but i download your files for the plugin for 5.1 and all i'm seeing is a folder with screenshots. In Aleksy's plugin, there's lots of other files that make up the plugin itself. Am i missing where to find these or did they somehow get removed from the files? 

thanks!
![Capture](https://user-images.githubusercontent.com/71304680/188536197-b1b3d530-6521-41e3-b312-c4c665988acd.PNG)

**Comment by nkuvyrkin** [comment]
Try downloading release https://github.com/nkuvyrkin/Ultimaker-Cura-v5.1-QIDI-X-CF-Pro-Plugin/releases/tag/v1.4.0
All files are there.

**Comment by nkuvyrkin** [comment]
Try downloading https://github.com/nkuvyrkin/Ultimaker-Cura-v5.1-QIDI-X-CF-Pro-Plugin/releases/download/v1.4.0/Ultimaker.Cura.QIDI.X-CF.Pro.zip
All files are there.

**Comment by 3dprintedmac** [comment]
That worked perfectly, thanks! Appreciate your work on getting the plug-in
up to date
