### ISSUE TITLE
New version of Cura doesn't display QidiPrint button

### ISSUE THREAD

**Issue by ebombme** [nkuvyrkin/Ultimaker-Cura-v5.x-QIDI-Printer-Plugin#8]
I know you put this up to help people, and probably don't have time to look after it. I'm a professional developer myself, so I really appreciate it.

 I'm just wondering if you might be able to tell me if the latest version of Cura (5.2.1) totally does away with the ability to get to the QidiPrint menu? I copied over both packages to their respective folders, and can't for the life of me find how I would get to the QidiPrint menu to connect to my network printer as shown in your directions. Only options are Networked Printer, and Non networked printer. No other buttons show up there. Any suggestions?

![Untitled](https://user-images.githubusercontent.com/35312673/211712799-b76e17b1-3c28-41f7-a3e1-cc51ebb218a8.png)

**Comment by kevsfastz** [comment]
@ebombme I was able to get this to work on the latest Cura release by copying the plugin release to:

%USERPROFILE%\AppData\Roaming\cura\5.2\plugins\

As opposed to the directory the readme suggests:

%USERPROFILE%\AppData\Roaming\cura\5.2.1\

**Comment by ebombme** [comment]
This worked. I could have sworn I already tried this. I'm pretty sure I did, but maybe I didn't do something else correctly. I had another issue on 4.12.1, and had to do the same thing to get it to work correctly a year ago. Thanks for the help, and the encouragement to try it again. Going to close the issue...
